export const ITEM_TEMPLATES = {
  gold: { id: 'gold', name: '金币', type: 'currency', value: 1 },

  potion_small: { id: 'potion_small', name: '小红药', type: 'consumable', hp: 60, mp: 0, price: 35 },
  potion_mid: { id: 'potion_mid', name: '中红药', type: 'consumable', hp: 140, mp: 0, price: 120 },
  potion_big: { id: 'potion_big', name: '大红药', type: 'consumable', hp: 300, mp: 0, price: 280 },
  potion_super: { id: 'potion_super', name: '超级金创药', type: 'consumable', hp: 550, mp: 0, price: 520 },
  potion_mana: { id: 'potion_mana', name: '小蓝药', type: 'consumable', hp: 0, mp: 50, price: 45 },
  potion_mana_mid: { id: 'potion_mana_mid', name: '中蓝药', type: 'consumable', hp: 0, mp: 120, price: 130 },
  potion_mana_big: { id: 'potion_mana_big', name: '大蓝药', type: 'consumable', hp: 0, mp: 260, price: 300 },
  potion_mana_super: { id: 'potion_mana_super', name: '超级魔法药', type: 'consumable', hp: 0, mp: 500, price: 520 },
  sun_water: { id: 'sun_water', name: '太阳水', type: 'consumable', hp: 200, mp: 200, price: 50000 },
  snow_frost: { id: 'snow_frost', name: '万年雪霜', type: 'consumable', hp: 600, mp: 600, price: 50000 },
  scroll_return: { id: 'scroll_return', name: '回城卷', type: 'consumable', teleport: { zone: 'bq_town', room: 'gate' }, price: 200 },
  scroll_random: { id: 'scroll_random', name: '随机卷', type: 'consumable', teleport: { zone: 'bq_plains', room: 'plains' }, price: 220 },
  scroll_recall: { id: 'scroll_recall', name: '召唤卷', type: 'consumable', price: 380 },

  training_fruit: { id: 'training_fruit', name: '修炼果', type: 'consumable', price: 1800, untradable: true, unconsignable: true },
  woma_horn: { id: 'woma_horn', name: '沃玛号角', type: 'material', price: 3000 },
  gold_bar: { id: 'gold_bar', name: '金条', type: 'material', price: 100000, rarity: 'epic' },
  book_war_basic: { id: 'book_war_basic', name: '技能书: 基本剑术', type: 'book', price: 800 },
  book_war_attack: { id: 'book_war_attack', name: '技能书: 攻杀剑术', type: 'book', price: 1200 },
  book_war_assassinate: { id: 'book_war_assassinate', name: '技能书: 刺杀剑术', type: 'book', price: 1800 },
  book_war_halfmoon: { id: 'book_war_halfmoon', name: '技能书: 半月弯刀', type: 'book', price: 2800 },
  book_war_fire: { id: 'book_war_fire', name: '技能书: 烈火剑法', type: 'book', price: 6800 },
  book_war_savage: { id: 'book_war_savage', name: '技能书: 野蛮冲撞', type: 'book', price: 5200 },
  book_war_earth_spike: { id: 'book_war_earth_spike', name: '技能书: 彻地钉', type: 'book', price: 9800, rarity: 'supreme', worldBossOnly: true },
  book_mage_fireball: { id: 'book_mage_fireball', name: '技能书: 小火球', type: 'book', price: 1200 },
  book_mage_resist: { id: 'book_mage_resist', name: '技能书: 抗拒火环', type: 'book', price: 1800 },
  book_mage_inferno: { id: 'book_mage_inferno', name: '技能书: 地狱火', type: 'book', price: 2200 },
  book_mage_explode: { id: 'book_mage_explode', name: '技能书: 爆裂火焰', type: 'book', price: 2800 },
  book_mage_lightning: { id: 'book_mage_lightning', name: '技能书: 雷电术', type: 'book', price: 4800 },
  book_mage_flash: { id: 'book_mage_flash', name: '技能书: 疾光电影', type: 'book', price: 5200 },
  book_mage_thunder: { id: 'book_mage_thunder', name: '技能书: 地狱雷光', type: 'book', price: 6200 },
  book_mage_thunderstorm: { id: 'book_mage_thunderstorm', name: '技能书: 雷霆万钧', type: 'book', price: 9800, rarity: 'supreme', worldBossOnly: true },
  book_mage_shield: { id: 'book_mage_shield', name: '技能书: 魔法盾', type: 'book', price: 8800 },
  book_mage_ice: { id: 'book_mage_ice', name: '技能书: 冰咆哮', type: 'book', price: 9800 },
  book_tao_heal: { id: 'book_tao_heal', name: '技能书: 治愈术', type: 'book', price: 1400 },
  book_tao_group_heal: { id: 'book_tao_group_heal', name: '技能书: 群体治疗术', type: 'book', price: 8200 },
  book_tao_poison: { id: 'book_tao_poison', name: '技能书: 施毒术', type: 'book', price: 3800 },
  book_tao_soul: { id: 'book_tao_soul', name: '技能书: 灵魂火符', type: 'book', price: 6200 },
  book_tao_invis: { id: 'book_tao_invis', name: '技能书: 隐身术', type: 'book', price: 5200 },
  book_tao_group_invis: { id: 'book_tao_group_invis', name: '技能书: 群体隐身术', type: 'book', price: 8200 },
  book_tao_armor: { id: 'book_tao_armor', name: '技能书: 神圣战甲术', type: 'book', price: 5200 },
  book_tao_shield: { id: 'book_tao_shield', name: '技能书: 幽灵盾', type: 'book', price: 5200 },
  book_tao_skeleton: { id: 'book_tao_skeleton', name: '技能书: 召唤骷髅', type: 'book', price: 5200 },
  book_tao_summon: { id: 'book_tao_summon', name: '技能书: 召唤神兽', type: 'book', price: 12000 },
  book_tao_white_tiger: { id: 'book_tao_white_tiger', name: '技能书: 召唤白虎', type: 'book', price: 15000, rarity: 'supreme', worldBossOnly: true },

  // Warrior weapons
  sword_wood: { id: 'sword_wood', name: '木剑', type: 'weapon', slot: 'weapon', atk: 2, price: 120 },
  dagger: { id: 'dagger', name: '匕首', type: 'weapon', slot: 'weapon', atk: 1, price: 80 },
  short_sword: { id: 'short_sword', name: '短剑', type: 'weapon', slot: 'weapon', atk: 2, price: 260 },
  scimitar: { id: 'scimitar', name: '凌风', type: 'weapon', slot: 'weapon', atk: 4, price: 520 },
  sword_iron: { id: 'sword_iron', name: '铁剑', type: 'weapon', slot: 'weapon', atk: 4, price: 420 },
  sabre: { id: 'sabre', name: '乌木剑', type: 'weapon', slot: 'weapon', atk: 5, price: 880 },
  bronze_sword: { id: 'bronze_sword', name: '青铜剑', type: 'weapon', slot: 'weapon', atk: 7, price: 1200 },
  steel_sword: { id: 'steel_sword', name: '钢剑', type: 'weapon', slot: 'weapon', atk: 8, price: 1800 },
  giant_sword: { id: 'giant_sword', name: '斩马刀', type: 'weapon', slot: 'weapon', atk: 9, price: 2600 },
  great_sword: { id: 'great_sword', name: '修罗', type: 'weapon', slot: 'weapon', atk: 10, price: 4200 },
  hatchet: { id: 'hatchet', name: '战斧', type: 'weapon', slot: 'weapon', atk: 9, price: 3200 },
  double_axe: { id: 'double_axe', name: '炼狱战斧', type: 'weapon', slot: 'weapon', atk: 12, price: 8200 },
  moonblade: { id: 'moonblade', name: '井中月', type: 'weapon', slot: 'weapon', atk: 11, price: 8200 },
  lianyu: { id: 'lianyu', name: '炼狱', type: 'weapon', slot: 'weapon', atk: 15, price: 16000 },
  juejudao: { id: 'juejudao', name: '裁决之杖', type: 'weapon', slot: 'weapon', atk: 21, price: 52000 },
  nujian: { id: 'nujian', name: '怒斩', type: 'weapon', slot: 'weapon', atk: 19, dex: 4, price: 72000 },
  wulong: { id: 'wulong', name: '屠龙', type: 'weapon', slot: 'weapon', atk: 31, price: 200000, rarity: 'epic' },
  kaitian: { id: 'kaitian', name: '开天', type: 'weapon', slot: 'weapon', atk: 47, price: 300000, rarity: 'legendary', bossOnly: true },
  sword_rochie: { id: 'sword_rochie', name: '洛奇王者之刃', type: 'weapon', slot: 'weapon', atk: 94, price: 600000, rarity: 'supreme', worldBossOnly: true },
  staff_rochie: { id: 'staff_rochie', name: '洛奇王者权杖', type: 'weapon', slot: 'weapon', mag: 66, price: 600000, rarity: 'supreme', worldBossOnly: true },
  sword_rochie_tao: { id: 'sword_rochie_tao', name: '洛奇王者之剑', type: 'weapon', slot: 'weapon', spirit: 66, price: 600000, rarity: 'supreme', worldBossOnly: true },

  // Mage weapons
  staff_apprentice: { id: 'staff_apprentice', name: '学徒法杖', type: 'weapon', slot: 'weapon', atk: 2, mag: 4, price: 380 },
  wand_ocean: { id: 'wand_ocean', name: '海魂', type: 'weapon', slot: 'weapon', mag: 5, price: 1600 },
  crescent_staff: { id: 'crescent_staff', name: '偃月', type: 'weapon', slot: 'weapon', mag: 8, price: 3600 },
  bone_wand: { id: 'bone_wand', name: '骨棒', type: 'weapon', slot: 'weapon', mag: 6, price: 1800 },
  magestaff: { id: 'magestaff', name: '魔杖', type: 'weapon', slot: 'weapon', mag: 10, price: 12000 },
  bone_staff: { id: 'bone_staff', name: '骨玉权杖', type: 'weapon', slot: 'weapon', mag: 18, price: 36000 },
  blood_drink: { id: 'blood_drink', name: '血饮', type: 'weapon', slot: 'weapon', mag: 22, price: 52000 },
  zhentian: { id: 'zhentian', name: '镇天', type: 'weapon', slot: 'weapon', mag: 33, price: 78000, rarity: 'legendary', bossOnly: true },

  // Taoist weapons
  talisman_bone: { id: 'talisman_bone', name: '骨符', type: 'weapon', slot: 'weapon', atk: 1, spirit: 3, price: 360 },
  bronze_talisman: { id: 'bronze_talisman', name: '青铜剑', type: 'weapon', slot: 'weapon', spirit: 6, price: 1800 },
  daosword: { id: 'daosword', name: '降魔', type: 'weapon', slot: 'weapon', spirit: 8, price: 5200 },
  silver_snake: { id: 'silver_snake', name: '银蛇', type: 'weapon', slot: 'weapon', spirit: 10, price: 14000 },
  wujigun: { id: 'wujigun', name: '无极棍', type: 'weapon', slot: 'weapon', spirit: 14, price: 26000 },
  longwen: { id: 'longwen', name: '龙纹剑', type: 'weapon', slot: 'weapon', spirit: 22, price: 52000 },
  xuantian: { id: 'xuantian', name: '玄天', type: 'weapon', slot: 'weapon', spirit: 33, price: 78000, rarity: 'legendary', bossOnly: true },

  // Armors
  armor_cloth: { id: 'armor_cloth', name: '布衣', type: 'armor', slot: 'chest', def: 2, price: 160 },
  armor_leather: { id: 'armor_leather', name: '皮甲', type: 'armor', slot: 'chest', def: 4, price: 480 },
  armor_light: { id: 'armor_light', name: '轻型盔甲', type: 'armor', slot: 'chest', def: 6, price: 1200 },
  armor_bronze: { id: 'armor_bronze', name: '青铜甲', type: 'armor', slot: 'chest', def: 5, price: 520 },
  armor_chain: { id: 'armor_chain', name: '锁子甲', type: 'armor', slot: 'chest', def: 8, price: 1800 },
  armor_plate: { id: 'armor_plate', name: '战甲', type: 'armor', slot: 'chest', def: 14, price: 5800 },
  armor_heavy: { id: 'armor_heavy', name: '重盔甲', type: 'armor', slot: 'chest', def: 16, price: 8800 },
  armor_war: { id: 'armor_war', name: '战神盔甲', type: 'armor', slot: 'chest', def: 20, price: 18000 },
  armor_mage: { id: 'armor_mage', name: '法神披风', type: 'armor', slot: 'chest', def: 19, dex: 2, mag: 6, price: 18000, bossOnly: true },
  armor_tao: { id: 'armor_tao', name: '天尊道袍', type: 'armor', slot: 'chest', def: 21, dex: 2, spirit: 6, price: 18000, bossOnly: true },
  armor_doom: { id: 'armor_doom', name: '幽灵战衣', type: 'armor', slot: 'chest', def: 21, dex: 2, spirit: 3, price: 12000 },
  armor_magic: { id: 'armor_magic', name: '恶魔长袍', type: 'armor', slot: 'chest', def: 19, dex: 2, mag: 3, price: 12000 },
  armor_taishan: { id: 'armor_taishan', name: '圣战宝甲', type: 'armor', slot: 'chest', def: 22, atk: 2, price: 52000, bossOnly: true },
  armor_thunder: { id: 'armor_thunder', name: '雷霆战甲', type: 'armor', slot: 'chest', def: 33, atk: 3, price: 78000, rarity: 'legendary', bossOnly: true },
  armor_flame: { id: 'armor_flame', name: '烈焰魔衣', type: 'armor', slot: 'chest', def: 29, dex: 3, mag: 9, price: 27000, rarity: 'legendary', bossOnly: true },
  armor_glow: { id: 'armor_glow', name: '光芒道袍', type: 'armor', slot: 'chest', def: 32, dex: 3, spirit: 9, price: 27000, rarity: 'legendary', bossOnly: true },
  armor_rochie_war: { id: 'armor_rochie_war', name: '洛奇战甲', type: 'armor', slot: 'chest', def: 44, atk: 6, price: 150000, rarity: 'supreme', worldBossOnly: true },
  armor_rochie_mage: { id: 'armor_rochie_mage', name: '洛奇法袍', type: 'armor', slot: 'chest', def: 38, dex: 6, mag: 18, price: 150000, rarity: 'supreme', worldBossOnly: true },
  armor_rochie_tao: { id: 'armor_rochie_tao', name: '洛奇道袍', type: 'armor', slot: 'chest', def: 42, dex: 6, spirit: 12, price: 150000, rarity: 'supreme', worldBossOnly: true },
  armor_molong: { id: 'armor_molong', name: '魔龙战甲', type: 'armor', slot: 'chest', def: 24, atk: 2, price: 42000 },

  // Helms
  helm_cloth: { id: 'helm_cloth', name: '布头盔', type: 'armor', slot: 'head', def: 1, price: 120 },
  helm_iron: { id: 'helm_iron', name: '铁盔', type: 'armor', slot: 'head', def: 3, price: 680 },
  helm_skull: { id: 'helm_skull', name: '骷髅头盔', type: 'armor', slot: 'head', def: 4, price: 1200 },
  helm_mystic: { id: 'helm_mystic', name: '道士头盔', type: 'armor', slot: 'head', def: 5, dex: 1, spirit: 1, price: 1600 },
  helm_wizard: { id: 'helm_wizard', name: '法师头盔', type: 'armor', slot: 'head', def: 5, dex: 1, mag: 1, price: 1600 },
  helm_war: { id: 'helm_war', name: '战神头盔', type: 'armor', slot: 'head', def: 6, price: 4800 },
  helm_mage: { id: 'helm_mage', name: '法神头盔(套)', type: 'armor', slot: 'head', def: 6, dex: 1, mag: 2, price: 4800, bossOnly: true },
  helm_sacred: { id: 'helm_sacred', name: '圣魔头盔(套)', type: 'armor', slot: 'head', def: 9, dex: 2, mag: 3, price: 7200, rarity: 'legendary', bossOnly: true },
  helm_tao: { id: 'helm_tao', name: '天尊头盔(套)', type: 'armor', slot: 'head', def: 6, dex: 1, spirit: 2, price: 4800, bossOnly: true },
  helm_true: { id: 'helm_true', name: '真魂头盔(套)', type: 'armor', slot: 'head', def: 9, dex: 2, spirit: 3, price: 7200, rarity: 'legendary', bossOnly: true },
  helm_rochie_war: { id: 'helm_rochie_war', name: '洛奇头盔(战士)', type: 'armor', slot: 'head', def: 22, atk: 4, price: 150000, rarity: 'supreme', worldBossOnly: true },
  helm_rochie_mage: { id: 'helm_rochie_mage', name: '洛奇头盔(法师)', type: 'armor', slot: 'head', def: 18, dex: 4, mag: 6, price: 150000, rarity: 'supreme', worldBossOnly: true },
  helm_rochie_tao: { id: 'helm_rochie_tao', name: '洛奇头盔(道士)', type: 'armor', slot: 'head', def: 18, dex: 4, spirit: 6, price: 150000, rarity: 'supreme', worldBossOnly: true },
  helm_holy: { id: 'helm_holy', name: '圣战头盔(套)', type: 'armor', slot: 'head', def: 7, atk: 1, price: 12000, bossOnly: true },
  helm_wargod: { id: 'helm_wargod', name: '战神头盔(套)', type: 'armor', slot: 'head', def: 11, atk: 2, price: 18000, rarity: 'legendary', bossOnly: true },

  // Boots
  boots_leather: { id: 'boots_leather', name: '皮靴', type: 'armor', slot: 'feet', def: 1, price: 120 },
  boots_iron: { id: 'boots_iron', name: '铁靴', type: 'armor', slot: 'feet', def: 3, price: 800 },
  boots_war: { id: 'boots_war', name: '战神靴', type: 'armor', slot: 'feet', def: 6, price: 4600 },
  boots_mage: { id: 'boots_mage', name: '法神靴(套)', type: 'armor', slot: 'feet', def: 6, dex: 1, mag: 2, price: 4600, bossOnly: true },
  boots_sacred: { id: 'boots_sacred', name: '圣魔靴子(套)', type: 'armor', slot: 'feet', def: 9, dex: 2, mag: 3, price: 6900, rarity: 'legendary', bossOnly: true },
  boots_tao: { id: 'boots_tao', name: '天尊靴(套)', type: 'armor', slot: 'feet', def: 6, dex: 1, spirit: 2, price: 4600, bossOnly: true },
  boots_true: { id: 'boots_true', name: '真魂靴子(套)', type: 'armor', slot: 'feet', def: 9, dex: 2, spirit: 3, price: 6900, rarity: 'legendary', bossOnly: true },
  boots_rochie_war: { id: 'boots_rochie_war', name: '洛奇靴子(战士)', type: 'armor', slot: 'feet', def: 22, atk: 4, price: 150000, rarity: 'supreme', worldBossOnly: true },
  boots_rochie_mage: { id: 'boots_rochie_mage', name: '洛奇靴子(法师)', type: 'armor', slot: 'feet', def: 18, dex: 4, mag: 6, price: 150000, rarity: 'supreme', worldBossOnly: true },
  boots_rochie_tao: { id: 'boots_rochie_tao', name: '洛奇靴子(道士)', type: 'armor', slot: 'feet', def: 18, dex: 4, spirit: 6, price: 150000, rarity: 'supreme', worldBossOnly: true },
  boots_holy: { id: 'boots_holy', name: '圣战靴(套)', type: 'armor', slot: 'feet', def: 7, atk: 1, price: 12000, bossOnly: true },
  boots_wargod: { id: 'boots_wargod', name: '战神靴子(套)', type: 'armor', slot: 'feet', def: 11, atk: 2, price: 18000, rarity: 'legendary', bossOnly: true },

  // Belts
  belt_cloth: { id: 'belt_cloth', name: '布腰带', type: 'armor', slot: 'waist', def: 1, price: 160 },
  belt_iron: { id: 'belt_iron', name: '铁腰带', type: 'armor', slot: 'waist', def: 3, price: 900 },
  belt_war: { id: 'belt_war', name: '战神腰带', type: 'armor', slot: 'waist', def: 6, price: 5200 },
  belt_mage: { id: 'belt_mage', name: '法神腰带(套)', type: 'armor', slot: 'waist', def: 6, dex: 1, mag: 2, price: 5200, bossOnly: true },
  belt_sacred: { id: 'belt_sacred', name: '圣魔腰带(套)', type: 'armor', slot: 'waist', def: 9, dex: 2, mag: 3, price: 7800, rarity: 'legendary', bossOnly: true },
  belt_tao: { id: 'belt_tao', name: '天尊腰带(套)', type: 'armor', slot: 'waist', def: 6, dex: 1, spirit: 2, price: 5200, bossOnly: true },
  belt_true: { id: 'belt_true', name: '真魂腰带(套)', type: 'armor', slot: 'waist', def: 9, dex: 2, spirit: 3, price: 7800, rarity: 'legendary', bossOnly: true },
  belt_rochie_war: { id: 'belt_rochie_war', name: '洛奇腰带(战士)', type: 'armor', slot: 'waist', def: 22, atk: 4, price: 150000, rarity: 'supreme', worldBossOnly: true },
  belt_rochie_mage: { id: 'belt_rochie_mage', name: '洛奇腰带(法师)', type: 'armor', slot: 'waist', def: 18, dex: 4, mag: 6, price: 150000, rarity: 'supreme', worldBossOnly: true },
  belt_rochie_tao: { id: 'belt_rochie_tao', name: '洛奇腰带(道士)', type: 'armor', slot: 'waist', def: 18, dex: 4, spirit: 6, price: 150000, rarity: 'supreme', worldBossOnly: true },
  belt_holy: { id: 'belt_holy', name: '圣战腰带(套)', type: 'armor', slot: 'waist', def: 7, atk: 1, price: 12000, bossOnly: true },
  belt_wargod: { id: 'belt_wargod', name: '战神腰带(套)', type: 'armor', slot: 'waist', def: 11, atk: 2, price: 18000, rarity: 'legendary', bossOnly: true },

  // Rings
  ring_copper: { id: 'ring_copper', name: '铜戒指', type: 'accessory', slot: 'ring', atk: 1, price: 260 },
  ring_platinum: { id: 'ring_platinum', name: '铂金戒指', type: 'accessory', slot: 'ring', atk: 2, price: 1800 },
  ring_coral: { id: 'ring_coral', name: '珊瑚戒指', type: 'accessory', slot: 'ring', atk: 3, price: 2800 },
  ring_ruby: { id: 'ring_ruby', name: '红宝石戒指', type: 'accessory', slot: 'ring', mag: 3, price: 3800 },
  ring_dodge: { id: 'ring_dodge', name: '躲避戒指', type: 'accessory', slot: 'ring', dex: 3, price: 4200 },
  ring_tiger: { id: 'ring_tiger', name: '骑士手镯', type: 'accessory', slot: 'bracelet', atk: 4, price: 6800 },
  ring_strength: { id: 'ring_strength', name: '力量戒指', type: 'accessory', slot: 'ring', atk: 6, price: 26000 },
  ring_bone: { id: 'ring_bone', name: '紫碧螺', type: 'accessory', slot: 'ring', mag: 6, price: 26000 },
  ring_tao: { id: 'ring_tao', name: '泰坦戒指', type: 'accessory', slot: 'ring', spirit: 6, dex: 1, price: 26000 },
  ring_holy: { id: 'ring_holy', name: '圣战戒指(套)', type: 'accessory', slot: 'ring', atk: 8, price: 48000, bossOnly: true },
  ring_wargod: { id: 'ring_wargod', name: '战神戒指(套)', type: 'accessory', slot: 'ring', atk: 12, price: 72000, rarity: 'legendary', bossOnly: true },
  ring_fashen: { id: 'ring_fashen', name: '法神戒指(套)', type: 'accessory', slot: 'ring', mag: 8, dex: 1, price: 48000, bossOnly: true },
  ring_sacred: { id: 'ring_sacred', name: '圣魔戒指(套)', type: 'accessory', slot: 'ring', mag: 12, dex: 2, price: 72000, rarity: 'legendary', bossOnly: true },
  ring_tianzun: { id: 'ring_tianzun', name: '天尊戒指(套)', type: 'accessory', slot: 'ring', spirit: 8, dex: 1, price: 48000, bossOnly: true },
  ring_true: { id: 'ring_true', name: '真魂戒指(套)', type: 'accessory', slot: 'ring', spirit: 12, dex: 2, price: 72000, rarity: 'legendary', bossOnly: true },
  ring_rochie_war: { id: 'ring_rochie_war', name: '洛奇戒指(战士)', type: 'accessory', slot: 'ring', atk: 24, price: 150000, rarity: 'supreme', worldBossOnly: true },
  ring_rochie_mage: { id: 'ring_rochie_mage', name: '洛奇戒指(法师)', type: 'accessory', slot: 'ring', mag: 24, dex: 4, price: 150000, rarity: 'supreme', worldBossOnly: true },
  ring_rochie_tao: { id: 'ring_rochie_tao', name: '洛奇戒指(道士)', type: 'accessory', slot: 'ring', spirit: 24, dex: 4, price: 150000, rarity: 'supreme', worldBossOnly: true },
  ring_def: { id: 'ring_def', name: '防御戒指', type: 'accessory', slot: 'ring', def: 4, price: 22000 },
  ring_fire: { id: 'ring_fire', name: '吸血戒指', type: 'accessory', slot: 'ring', mag: 4, price: 24000 },
  ring_heal: { id: 'ring_heal', name: '治愈戒指', type: 'accessory', slot: 'ring', spirit: 4, price: 24000 },
  ring_teleport: { id: 'ring_teleport', name: '弱化戒指', type: 'accessory', slot: 'ring', atk: 1, def: 1, mag: 1, spirit: 1, dex: 1, price: 80000, rarity: 'legendary', bossOnly: true },
  ring_protect: { id: 'ring_protect', name: '护身戒指', type: 'accessory', slot: 'ring', atk: 1, def: 1, mag: 1, spirit: 1, dex: 1, price: 80000, rarity: 'legendary', bossOnly: true },
  ring_revival: { id: 'ring_revival', name: '复活戒指', type: 'accessory', slot: 'ring', atk: 1, def: 1, mag: 1, spirit: 1, dex: 1, price: 80000, rarity: 'legendary', bossOnly: true },
  ring_magic: { id: 'ring_magic', name: '麻痹戒指', type: 'accessory', slot: 'ring', atk: 1, def: 1, mag: 1, spirit: 1, dex: 1, price: 80000, rarity: 'legendary', bossOnly: true },
  ring_recall: { id: 'ring_recall', name: '记忆戒指', type: 'accessory', slot: 'ring', spirit: 3, price: 28000 },
  ring_break: { id: 'ring_break', name: '破防戒指', type: 'accessory', slot: 'ring', atk: 1, def: 1, mag: 1, spirit: 1, dex: 1, price: 80000, rarity: 'legendary', bossOnly: true },

  // Necklaces
  necklace_jade: { id: 'necklace_jade', name: '玉项链', type: 'accessory', slot: 'neck', mag: 2, price: 300 },
  necklace_life: { id: 'necklace_life', name: '生命项链', type: 'accessory', slot: 'neck', atk: 2, price: 3800 },
  necklace_light: { id: 'necklace_light', name: '灯笼项链', type: 'accessory', slot: 'neck', def: 2, price: 1800 },
  necklace_memory: { id: 'necklace_memory', name: '记忆项链', type: 'accessory', slot: 'neck', spirit: 3, price: 28000 },
  necklace_green: { id: 'necklace_green', name: '绿色项链', type: 'accessory', slot: 'neck', atk: 4, price: 12000 },
  necklace_evil: { id: 'necklace_evil', name: '恶魔铃铛', type: 'accessory', slot: 'neck', def: 1, dex: 1, mag: 4, price: 12000 },
  necklace_tao: { id: 'necklace_tao', name: '灵魂项链', type: 'accessory', slot: 'neck', def: 1, dex: 1, spirit: 4, price: 12000 },
  necklace_ghost: { id: 'necklace_ghost', name: '幽灵项链', type: 'accessory', slot: 'neck', def: 1, dex: 1, spirit: 5, price: 16000 },
  necklace_soldier: { id: 'necklace_soldier', name: '圣战项链(套)', type: 'accessory', slot: 'neck', atk: 6, price: 48000, bossOnly: true },
  necklace_wargod: { id: 'necklace_wargod', name: '战神项链(套)', type: 'accessory', slot: 'neck', atk: 9, price: 72000, rarity: 'legendary', bossOnly: true },
  necklace_fashen: { id: 'necklace_fashen', name: '法神项链(套)', type: 'accessory', slot: 'neck', def: 1, dex: 1, mag: 6, price: 48000, bossOnly: true },
  necklace_sacred: { id: 'necklace_sacred', name: '圣魔项链(套)', type: 'accessory', slot: 'neck', def: 2, dex: 2, mag: 9, price: 72000, rarity: 'legendary', bossOnly: true },
  necklace_tianzun: { id: 'necklace_tianzun', name: '天尊项链(套)', type: 'accessory', slot: 'neck', def: 1, dex: 1, spirit: 6, price: 48000, bossOnly: true },
  necklace_true: { id: 'necklace_true', name: '真魂项链(套)', type: 'accessory', slot: 'neck', def: 2, dex: 2, spirit: 9, price: 72000, rarity: 'legendary', bossOnly: true },
  necklace_rochie_war: { id: 'necklace_rochie_war', name: '洛奇项链(战士)', type: 'accessory', slot: 'neck', atk: 18, price: 150000, rarity: 'supreme', worldBossOnly: true },
  necklace_rochie_mage: { id: 'necklace_rochie_mage', name: '洛奇项链(法师)', type: 'accessory', slot: 'neck', def: 4, dex: 4, mag: 18, price: 150000, rarity: 'supreme', worldBossOnly: true },
  necklace_rochie_tao: { id: 'necklace_rochie_tao', name: '洛奇项链(道士)', type: 'accessory', slot: 'neck', def: 4, dex: 4, spirit: 18, price: 150000, rarity: 'supreme', worldBossOnly: true },
  necklace_luck: { id: 'necklace_luck', name: '幸运项链', type: 'accessory', slot: 'neck', dex: 3, price: 26000 },

  // Bracelets
  bracelet_copper: { id: 'bracelet_copper', name: '铜手镯', type: 'accessory', slot: 'bracelet', def: 1, price: 280 },
  bracelet_iron: { id: 'bracelet_iron', name: '铁手镯', type: 'accessory', slot: 'bracelet', def: 2, price: 800 },
  bracelet_death: { id: 'bracelet_death', name: '死神手套', type: 'accessory', slot: 'bracelet', atk: 4, price: 6200 },
  bracelet_dragon: { id: 'bracelet_dragon', name: '龙之手镯', type: 'accessory', slot: 'bracelet', mag: 4, price: 6200 },
  bracelet_eye: { id: 'bracelet_eye', name: '三眼手镯', type: 'accessory', slot: 'bracelet', def: 1, dex: 1, spirit: 4, price: 6200 },
  bracelet_ghost: { id: 'bracelet_ghost', name: '幽灵手套', type: 'accessory', slot: 'bracelet', def: 1, dex: 1, spirit: 5, price: 12000 },
  bracelet_yanluo: { id: 'bracelet_yanluo', name: '阎罗手套', type: 'accessory', slot: 'bracelet', def: 4, price: 12000 },
  bracelet_soldier: { id: 'bracelet_soldier', name: '圣战手镯(套)', type: 'accessory', slot: 'bracelet', atk: 6, price: 48000, bossOnly: true },
  bracelet_wargod: { id: 'bracelet_wargod', name: '战神手镯(套)', type: 'accessory', slot: 'bracelet', atk: 9, price: 72000, rarity: 'legendary', bossOnly: true },
  bracelet_fashen: { id: 'bracelet_fashen', name: '法神手镯(套)', type: 'accessory', slot: 'bracelet', def: 1, dex: 1, mag: 6, price: 48000, bossOnly: true },
  bracelet_sacred: { id: 'bracelet_sacred', name: '圣魔手镯(套)', type: 'accessory', slot: 'bracelet', def: 2, dex: 2, mag: 9, price: 72000, rarity: 'legendary', bossOnly: true },
  bracelet_tianzun: { id: 'bracelet_tianzun', name: '天尊手镯(套)', type: 'accessory', slot: 'bracelet', def: 1, dex: 1, spirit: 6, price: 48000, bossOnly: true },
  bracelet_true: { id: 'bracelet_true', name: '真魂手镯(套)', type: 'accessory', slot: 'bracelet', def: 2, dex: 2, spirit: 9, price: 72000, rarity: 'legendary', bossOnly: true },
  bracelet_rochie_war: { id: 'bracelet_rochie_war', name: '洛奇手镯(战士)', type: 'accessory', slot: 'bracelet', atk: 18, price: 150000, rarity: 'supreme', worldBossOnly: true },
  bracelet_rochie_mage: { id: 'bracelet_rochie_mage', name: '洛奇手镯(法师)', type: 'accessory', slot: 'bracelet', def: 4, dex: 4, mag: 18, price: 150000, rarity: 'supreme', worldBossOnly: true },
  bracelet_rochie_tao: { id: 'bracelet_rochie_tao', name: '洛奇手镯(道士)', type: 'accessory', slot: 'bracelet', def: 4, dex: 4, spirit: 18, price: 150000, rarity: 'supreme', worldBossOnly: true }
};

export const SHOP_STOCKS = {
  bq_shop: ['potion_small', 'potion_mana', 'scroll_return', 'scroll_random', 'sword_wood', 'armor_cloth', 'boots_leather', 'ring_copper', 'bracelet_copper', 'helm_cloth', 'belt_cloth'],
  bq_blacksmith: ['sword_iron', 'sabre', 'armor_bronze', 'armor_chain', 'boots_iron', 'helm_iron', 'belt_iron'],
  bq_tao: ['talisman_bone', 'potion_mana', 'potion_mana_mid', 'scroll_return'],
  bq_mage: ['staff_apprentice', 'potion_mana', 'potion_mana_mid', 'scroll_return'],
  mg_shop: ['potion_mid', 'potion_big', 'potion_mana_mid', 'potion_mana_big', 'sun_water', 'snow_frost', 'scroll_return', 'scroll_random'],
  mg_blacksmith: ['moonblade', 'armor_plate', 'boots_iron', 'helm_skull', 'belt_iron'],
  mg_magic: ['wand_ocean', 'crescent_staff', 'necklace_jade', 'necklace_light', 'bracelet_iron'],
  mg_tao: ['bronze_talisman', 'daosword', 'necklace_ghost', 'bracelet_death']
};
